### ISSUE TITLE
no ReportPortalTestNGListener

### ISSUE THREAD

**Issue by auto110** [d3m0/automation#4]
`class MyListener extends ReportPortalTestNGListener
`

however, missed the ReportPortalTestNGListener in your source code

**Comment by d3m0** [comment]
Please make sure you have all dependencies imported. 
Class ReportPortalTestNGListener is in 

<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>agent-java-testng</artifactId>
    <version>5.0.8</version>
</dependency>
